spring:
  application:
    name: hoangcode
  profiles:
    active: development
  jackson:
    date-format: "yyyy/MM/dd"
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  servlet:
    multipart:
      enabled: true
      # Threshold after which files will be written to disk.
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 20MB
 
  main:
    allow-bean-definition-overriding: true
  resources:
    # Static resources reloading during development
    static-locations: classpath:/resources/static
    cache:
      period: 0

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        
application:
  path:
    upload: /Users/LeHuyHoang/tmp/upload
    download: /Users/LeHuyHoang/tmp/download
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
    